
// event_based_common_header.h
// 2019 Feb 05

#ifndef PITZ_DAQ_EVENT_BASED_COMMON_HEADER_H
#define PITZ_DAQ_EVENT_BASED_COMMON_HEADER_H

#define PITZ_DAQ_LIST_UPDATE_DEFAULT_TIME   600 // s

#ifndef PITZ_DAQ_UNKNOWN_DATA_TYPE
#define PITZ_DAQ_UNKNOWN_DATA_TYPE  -1
#endif  // #ifndef PITZ_DAQ_UNKNOWN_DATA_TYPE

#ifndef PITZ_DAQ_UNSPECIFIED_DATA_TYPE
#define PITZ_DAQ_UNSPECIFIED_DATA_TYPE  -1
#endif  // #ifndef PITZ_DAQ_UNKNOWN_DATA_TYPE

#ifndef PITZ_DAQ_UNSPECIFIED_NUMBER_OF_SAMPLES
#define PITZ_DAQ_UNSPECIFIED_NUMBER_OF_SAMPLES  -1
#endif  // #ifndef PITZ_DAQ_UNKNOWN_DATA_TYPE

#ifndef PITZ_DAQ_UNKNOWN_ZMQ_PORT
#define PITZ_DAQ_UNKNOWN_ZMQ_PORT  -1
#endif  // #ifndef PITZ_DAQ_UNKNOWN_ZMQ_PORT

#ifndef PITZ_DAQ_DATA_TYPE_MISMATCH
#define PITZ_DAQ_DATA_TYPE_MISMATCH  -1
#endif  // #ifndef PITZ_DAQ_UNKNOWN_ZMQ_PORT

#define PITZ_DAQ_EV_BASED_DCS_ZMQ_SYNTAX_ERROR  -2
#define PITZ_DAQ_EV_BASED_DCS_ZMQ_UNKNOWN_HEADER  -3


#endif // #ifndef PITZ_DAQ_EVENT_BASED_COMMON_HEADER_H
